default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    sh("flutter build ios --release --no-codesign")
    api_key = app_store_connect_api_key(
      in_house: false,
      is_key_content_base64: true
    )
    match(type: "appstore")
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
  upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
