default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    api_key = app_store_connect_api_key(
      in_house: false,
      is_key_content_base64: true
    )
    match(type: "appstore")
    get_certificates
    get_provisioning_profile
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
  upload_to_testflight()
  end
end
