# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Fetch dependencies and build the release APK"
  lane :build_release do
    sh("flutter pub get")
    sh("flutter build appbundle --release")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    build_release
    upload_to_play_store(track: 'internal', aab: "../build/app/outputs/bundle/release/app-release.aab", release_status: 'draft')
  end
end
