name: Android Fastlane

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Install Fastlane
      run: |
        sudo gem install fastlane -NV
       
    - name: Add ENV
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV }}
      run: echo $ENV_FILE_CONTENT > ${GITHUB_WORKSPACE}/.env

    - name: Create the Keystore
      working-directory: ./android
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: echo $KEYSTORE_BASE64 | base64 -di > app/production.keystore

    # Configure Keystore.
    - name: Configure Keystore
      working-directory: ./android
      run: |
        echo "storeFile=production.keystore" >> key.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
      env:
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Build APK
      working-directory: ./android
      run: fastlane android build_release

    - name: Internal Deployment to Play Store
      working-directory: ./android
      run: fastlane android internal
      env:
        PLAY_STORE_JSON_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}