name: Android Fastlane

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Install Fastlane
      run: |
        sudo gem install fastlane -NV
       

    - name: Build APK
      working-directory: ./android
      run: fastlane android build_release

    - name: Internal Deployment to Play Store
      working-directory: ./android
      run: fastlane android internal
      env:
        PLAY_STORE_JSON_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}