name: iOS Release Production

on: [workflow_call, workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
     
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Add ENV
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV }}
        run: echo $ENV_FILE_CONTENT > ${GITHUB_WORKSPACE}/.env

      - name: Internal Deployment to TestFlight
        working-directory: ./ios
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: fastlane ios beta

