name: iOS Release Production

on: [workflow_call, workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Install CocoaPods dependencies
        working-directory: ./ios
        run: |
          if [ -d "Pods" ]; then
            echo "Pods directory exists. Skipping pod install."
          else
            pod install
          fi

      - name: Add ENV
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo $API_KEYS > api-keys.json
          echo "SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN" >> $GITHUB_ENV

      - name: Internal Deployment to TestFlight
        working-directory: ./ios
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: fastlane ios beta

      - name: Upload debug symbols
        run: flutter packages pub run sentry_dart_plugin
