name: iOS Release Production

on: [workflow_call, workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          
      - name: Install CocoaPods dependencies
        working-directory: ./ios
        run:  |
          flutter pub get
          pod install

      - name: Add ENV
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV }}
        run: echo $ENV_FILE_CONTENT > ${GITHUB_WORKSPACE}/.env

      - name: Internal Deployment to TestFlight
        working-directory: ./ios
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: fastlane ios beta

